# Generated by Django 5.2.7 on 2025-10-28 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос голосования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Количество голосов')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='post.poll', verbose_name='Голосование')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
                ('visibility', models.CharField(choices=[('all_users', 'Все пользователи'), ('subscribers_only', 'Только подписчики'), ('one_time_payment', 'Разовая оплата')], default='all_users', max_length=20, verbose_name='Видимость')),
                ('is_ad', models.BooleanField(default=False, verbose_name='Рекламный пост')),
                ('ad_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание рекламодателя')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланированное время публикации')),
                ('comments_disabled', models.BooleanField(default=False, verbose_name='Отключить комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='post.tag', verbose_name='Теги')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='post.post', verbose_name='Пост'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио')], max_length=10, verbose_name='Тип медиа')),
                ('file', models.FileField(upload_to='posts/media/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='post.post', verbose_name='Пост')),
            ],
        ),
    ]
