# Generated by Django 5.2 on 2025-11-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment'),
        ('subscription', '0002_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Если выбрана подписка, пост будет доступен только подписчикам', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('all_users', 'Все пользователи')], default='all_users', max_length=20, verbose_name='Видимость'),
        ),
    ]
