# Generated by Django 4.2.7 on 2025-12-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_options_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Комментарий, на который отвечаем (только для отображения)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_to', to='post.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='post.comment'),
        ),
    ]
