# Generated by Django 4.2.7 on 2025-12-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_reply_to_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
