# Generated by Django 5.2 on 2025-11-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название подписки')),
                ('description', models.TextField(verbose_name='Описание подписки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за месяц')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscriptions/%Y/%m/%d/', verbose_name='Иллюстрация подписки')),
                ('is_limited_subscribers', models.BooleanField(default=False, verbose_name='Ограниченное количество подписчиков')),
                ('max_subscribers', models.PositiveIntegerField(default=1000, verbose_name='Максимальное количество подписчиков')),
                ('is_discount_active', models.BooleanField(default=False, verbose_name='Активирована скидка')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Процент скидки')),
                ('has_trial_period', models.BooleanField(default=False, verbose_name='Есть пробный период')),
                ('trial_days', models.PositiveIntegerField(default=14, verbose_name='Дни пробного периода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
    ]
