# Generated by Django 4.2.7 on 2025-12-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Подписка пользователя', 'verbose_name_plural': 'Подписки пользователей'},
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='subscription.subscription'),
        ),
    ]
