# Generated by Django 5.2.7 on 2025-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='current_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Текущая сумма'),
        ),
    ]
