# Generated by Django 5.2.7 on 2025-10-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usergoal_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='current_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущая сумма'),
        ),
    ]
