# Generated by Django 5.2.7 on 2025-10-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privacy_policy_agreed',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности'),
        ),
    ]
