# Generated by Django 5.2.7 on 2025-10-30 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_privacy_policy_agreed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vk_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='youtube_link',
        ),
        migrations.CreateModel(
            name='UserSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('tiktok', models.URLField(blank=True, max_length=100, null=True, verbose_name='TikTok')),
                ('youtube', models.URLField(blank=True, max_length=100, null=True, verbose_name='YouTube')),
                ('vk', models.URLField(blank=True, max_length=100, null=True, verbose_name='VK')),
                ('x', models.URLField(blank=True, max_length=100, null=True, verbose_name='X')),
                ('b', models.URLField(blank=True, max_length=100, null=True, verbose_name='B')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('behance', models.URLField(blank=True, max_length=100, null=True, verbose_name='Behance')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
