# Generated by Django 5.2.7 on 2025-11-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_customuser_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersociallinks',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='usersociallinks',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='usersociallinks',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='usersociallinks',
            name='x',
        ),
    ]
